### PR TITLE
[debian] Create debian packaging information

### PR DESCRIPTION
**Pull request by braiam**
There's some miscelaneous fixes that needs to be
applied for a full compliance. But this is enough
to create a package.

Full policy:
https://wiki.debian.org/Python/LibraryStyleGuide

---
This change is [Reviewable](https://reviewable.io/reviews/cdberkstresser/fah-control/6)

### CODE REVIEW

**Comment by cdberkstresser** [comment]
I'm hoping to hear back from jcoffland about the main pr. I believe he is using stdeb, but I assume that isn't set in stone. I'm hoping to hear back if he wants to merge this as a central core change and do a separate PR for packaging or wait to do them all.

**Comment by braiam** [comment]
I know, I plan to submit a RFP to Debian so it's included in the contrib repositories (hopping that the project also frees the client code). My pr was most about the response to the issue that there are no binaries.

**Comment by braiam** [comment]
According to https://github.com/FoldingAtHome/fah-web-client/issues/15#issuecomment-602164495 they will release the client as opensource, so it seems that this work would be useful to include everything in distros.

**Comment by cdberkstresser** [comment]
Have heard from jcoffland today and he is hoping to review the PR soon...  Would love these all to be as easy as `sudo apt install fahclient` or sudo yum install fahclient` with the open sourcing @braiam mentioned.

**Comment by cdberkstresser** [comment]
These look good @braiam .  Going to go ahead and run with this since Ubuntu 20.04 is out and people are asking for builds.  Made some minor changes to version number and compat.

**Pull request merged**
